//
// vertex_shader.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_VERTEX_SHADER_H
#define ISPC_VERTEX_SHADER_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT_float3__
#define __ISPC_STRUCT_float3__
struct float3 {
    float x;
    float y;
    float z;
    float pad0;
};
#endif

#ifndef __ISPC_STRUCT_VertexInput__
#define __ISPC_STRUCT_VertexInput__
struct VertexInput {
    struct float3 Position;
    struct float3 Color;
};
#endif

#ifndef __ISPC_STRUCT_float4__
#define __ISPC_STRUCT_float4__
struct float4 {
    float x;
    float y;
    float z;
    float w;
};
#endif

#ifndef __ISPC_STRUCT_VertexOutput__
#define __ISPC_STRUCT_VertexOutput__
struct VertexOutput {
    struct float4 Position;
    struct float3 Color;
};
#endif

#ifndef __ISPC_STRUCT_matrix4x4__
#define __ISPC_STRUCT_matrix4x4__
struct matrix4x4 {
    float m[4][4];
};
#endif

#ifndef __ISPC_STRUCT_Constants__
#define __ISPC_STRUCT_Constants__
struct Constants {
    struct matrix4x4 WorldMatrix;
    struct matrix4x4 ViewMatrix;
    struct matrix4x4 ProjectionMatrix;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void vertex_shader(struct VertexInput * input, struct VertexOutput * output, int32_t count, const struct Constants &constants);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_VERTEX_SHADER_H
